#pragma once

#define IPMIDI_NAMESPACE ipMidi
#define BEGIN_IPMIDI_NAMESPACE \
    namespace IPMIDI_NAMESPACE \
    {
#define END_IPMIDI_NAMESPACE }

#define USING_NAMESPACE_IPMIDI using namespace IPMIDI_NAMESPACE;

BEGIN_IPMIDI_NAMESPACE

END_IPMIDI_NAMESPACE
